version: "3.8"
services: 
  database:
    image: postgres:alpine
    ports:
      - 15432:5432
    environment: 
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
      POSTGRES_DB: demo
